version: "2"
services:
  app:
    image: "jemjem7/poster:latest"
    ports:
      - "90:3000"
    volumes:
      - /home/jem/projects/poster:/usr/src/app/poster
      - ${PWD}/admin-db.sqlite:/usr/src/app/
    environment:
      DB_LOGIN: ${DB_LOGIN}
      DB_PASS: ${DB_PASS}