name: Deploy

on:
 push:
  tags:
    - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}

      #build
      - run: npm install
      - run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/poster:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      #setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
  
      - run: rsync -v docker-compose.yml -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --no-recursive . ${{ secrets.SERVER_USER }}@104.131.43.62:/home/jem/projects/admin-poster
      #- run: rsync -v admin-db.sqlite -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --no-recursive . ${{ secrets.SERVER_USER }}@104.131.43.62:/home/jem/projects/admin-poster

      - name: run app
        uses: appleboy/ssh-action@master
        env:
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
          DB_PASS: ${{ secrets.DB_PASS }}
        with:
          host: 104.131.43.62
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.key }}
          envs: DOCKER_HUB_ACCESS_TOKEN,DOCKER_HUB_USERNAME,DB_LOGIN,DB_PASS
          script: |
            cd /home/jem/projects/admin-poster
            echo $DB_PASS
            echo $DOCKER_HUB_ACCESS_TOKEN | docker login --password-stdin -u $DOCKER_HUB_USERNAME
            docker-compose pull
            docker-compose stop
            docker-compose rm -f
            docker-compose up -d

